[package]
name = "private_voting"
type = "contract"
authors = [""]
compiler_version = ">=0.31.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages", tag="aztec-packages-v0.45.1", directory="noir-projects/aztec-nr/aztec" }